
CREATE TABLE public.error_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  error_message TEXT,
  stack_trace TEXT,
  component VARCHAR(255),
  user_agent TEXT,
  user_id UUID
);

ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

-- Allow service_role to perform all actions.
-- This will be used by an edge function to insert logs.
CREATE POLICY "Allow full access for service_role"
ON public.error_logs
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

