
-- Create a new ENUM type for health status
CREATE TYPE public.health_status AS ENUM ('ok', 'warning', 'error');

-- Create table for System Health Logs
CREATE TABLE public.system_health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    component TEXT NOT NULL,
    status public.health_status NOT NULL,
    details TEXT
);

COMMENT ON TABLE public.system_health_logs IS 'Stores logs from system health checks.';

-- Enable RLS for System Health Logs
ALTER TABLE public.system_health_logs ENABLE ROW LEVEL SECURITY;

-- Policies for system_health_logs
CREATE POLICY "Admin and supervisors can view system health logs"
    ON public.system_health_logs FOR SELECT
    USING (
        (public.has_role(auth.uid(), 'admin')) OR
        (public.has_role(auth.uid(), 'supervisor'))
    );

CREATE POLICY "Admin and supervisors can insert system health logs"
    ON public.system_health_logs FOR INSERT
    WITH CHECK (
        (public.has_role(auth.uid(), 'admin')) OR
        (public.has_role(auth.uid(), 'supervisor'))
    );
