// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwalfohkwbufyxvmyuqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YWxmb2hrd2J1Znl4dm15dXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ3MTMsImV4cCI6MjA2NTQ3MDcxM30.-9e-POpfw1qCw9I8lxExdYcnsZTZTFMm90nwGBlLgKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);